"""
Punchestown 3:05 Race Data
Extracted from user's betting app screenshots
"""

race_data = {
    "race_details": {
        "track": "Punchestown",
        "time": "15:05",
        "race_type": "Handicap",
        "distance": "Unknown",  # Not visible in screenshots
        "going": "Unknown",  # Not visible in screenshots
        "field_size": 13
    },
    "horses": [
        {
            "number": 5,
            "name": "Captain Ryan Matt",
            "jockey": "Darragh O'Keeffe",
            "trainer": "H De Bromhead",
            "form": "522-15",
            "weight": "11-4",
            "age": 5,
            "odds": 5.0,
            "official_rating": 117,
            "rpr": 117,
            "topspeed": None,
            "trainer_stats": {"roi": 6.28, "wins": 7, "runs": 19, "strike_rate": 37},
            "jockey_stats": {"roi": 32.28, "wins": 6, "runs": 34, "strike_rate": 18},
            "race_comments": []
        },
        {
            "number": 7,
            "name": "Serienmond",
            "jockey": "Keith Donoghue",
            "trainer": "G P Cromwell",
            "form": "136-17",
            "weight": "11-4",
            "age": 5,
            "odds": 5.5,
            "official_rating": 117,
            "rpr": 121,
            "topspeed": None,
            "trainer_stats": {"roi": -9.99, "wins": 9, "runs": 41, "strike_rate": 22},
            "jockey_stats": {"roi": -3.23, "wins": 7, "runs": 29, "strike_rate": 24},
            "race_comments": []
        },
        {
            "number": 12,
            "name": "Avalo",
            "jockey": "Sam Ewing",
            "trainer": "Peter Fahey",
            "form": "162332",
            "weight": "10-11",
            "age": 6,
            "odds": 5.5,
            "official_rating": 110,
            "rpr": 108,
            "topspeed": None,
            "trainer_stats": {"roi": -6.00, "wins": 1, "runs": 10, "strike_rate": 10},
            "jockey_stats": {"roi": -5.25, "wins": 3, "runs": 18, "strike_rate": 17},
            "race_comments": []
        },
        {
            "number": 11,
            "name": "Ballycashin",
            "jockey": "Anna McGuinness (7)",
            "trainer": "A Mullins",
            "form": "-32663",
            "weight": "10-13",
            "age": 8,
            "odds": 6.5,
            "official_rating": 112,
            "rpr": 111,
            "topspeed": None,
            "trainer_stats": {"roi": 1.00, "wins": 1, "runs": 3, "strike_rate": 33},
            "jockey_stats": {"roi": -5.00, "wins": 0, "runs": 5, "strike_rate": 0},
            "race_comments": []
        },
        {
            "number": 1,
            "name": "Nine Graces",
            "jockey": "Mr F Maguire",
            "trainer": "B Connell",
            "form": "30210-",
            "weight": "11-12",
            "age": 8,
            "odds": 8.5,
            "official_rating": 125,
            "rpr": 133,
            "topspeed": None,
            "trainer_stats": {"roi": 5.94, "wins": 0, "runs": 3, "strike_rate": 0},
            "jockey_stats": {"roi": -3.00, "wins": 0, "runs": 3, "strike_rate": 0},
            "race_comments": []
        },
        {
            "number": 4,
            "name": "Rockymountainbleu",
            "jockey": "Tiernan Power Roche (5)",
            "trainer": "P J Rothwell",
            "form": "3445-8",
            "weight": "11-6",
            "age": 7,
            "odds": 9.0,
            "official_rating": 119,
            "rpr": 125,
            "topspeed": None,
            "trainer_stats": {"roi": 0.33, "wins": 1, "runs": 28, "strike_rate": 4},
            "jockey_stats": {"roi": 82.83, "wins": 0, "runs": 25, "strike_rate": 0},
            "race_comments": []
        },
        {
            "number": 3,
            "name": "Saint Le Fort",
            "jockey": "Niall Moore (5)",
            "trainer": "P Fenton",
            "form": "2315-9",
            "weight": "11-7",
            "age": 5,
            "odds": 13.0,
            "official_rating": 120,
            "rpr": 122,
            "topspeed": None,
            "trainer_stats": {"roi": -6.00, "wins": 0, "runs": 6, "strike_rate": 0},
            "jockey_stats": {"roi": -5.00, "wins": 0, "runs": 5, "strike_rate": 0},
            "race_comments": []
        },
        {
            "number": 6,
            "name": "My Gaffer",
            "jockey": "Danny Mullins",
            "trainer": "J P Ryan",
            "form": "205175",
            "weight": "11-4",
            "age": 7,
            "odds": 15.0,
            "official_rating": 117,
            "rpr": 125,
            "topspeed": None,
            "trainer_stats": {"roi": -13.88, "wins": 2, "runs": 22, "strike_rate": 9},
            "jockey_stats": {"roi": -20.00, "wins": 1, "runs": 24, "strike_rate": 4},
            "race_comments": []
        },
        {
            "number": 8,
            "name": "Fortunate Lighting",
            "jockey": "Alex Harvey",
            "trainer": "Thomas Coyle",
            "form": "5-6516",
            "weight": "11-1",
            "age": 7,
            "odds": 17.0,
            "official_rating": 114,
            "rpr": 114,
            "topspeed": None,
            "trainer_stats": {"roi": 0.00, "wins": 0, "runs": 0, "strike_rate": 0},
            "jockey_stats": {"roi": -11.50, "wins": 1, "runs": 16, "strike_rate": 6},
            "race_comments": []
        },
        {
            "number": 13,
            "name": "Giant Haystacks",
            "jockey": "Danny Gilligan",
            "trainer": "R O'Sullivan",
            "form": "1PP-08",
            "weight": "10-8",
            "age": 6,
            "odds": 17.0,
            "official_rating": 107,
            "rpr": 112,
            "topspeed": None,
            "trainer_stats": {"roi": -3.25, "wins": 1, "runs": 7, "strike_rate": 14},
            "jockey_stats": {"roi": 7.83, "wins": 3, "runs": 17, "strike_rate": 18},
            "race_comments": []
        },
        {
            "number": 9,
            "name": "Golden Temple",
            "jockey": "Donagh Meyler",
            "trainer": "N Meade",
            "form": "0-0409",
            "weight": "11-1",
            "age": 5,
            "odds": 21.0,
            "official_rating": 114,
            "rpr": 126,
            "topspeed": None,
            "trainer_stats": {"roi": -8.00, "wins": 0, "runs": 8, "strike_rate": 0},
            "jockey_stats": {"roi": 4.88, "wins": 5, "runs": 27, "strike_rate": 19},
            "race_comments": []
        },
        {
            "number": 10,
            "name": "Linden Arden",
            "jockey": "Brian Hayes",
            "trainer": "D H Kelly",
            "form": "13-F9P",
            "weight": "11-1",
            "age": 7,
            "odds": 21.0,
            "official_rating": 114,
            "rpr": 130,
            "topspeed": None,
            "trainer_stats": {"roi": -5.43, "wins": 2, "runs": 10, "strike_rate": 20},
            "jockey_stats": {"roi": -3.18, "wins": 3, "runs": 11, "strike_rate": 27},
            "race_comments": []
        },
        {
            "number": 2,
            "name": "Indiana Jones",
            "jockey": "G Brouder (3)",
            "trainer": "M F Morris",
            "form": "6477-0",
            "weight": "11-8",
            "age": 9,
            "odds": 29.0,
            "official_rating": 121,
            "rpr": 140,
            "topspeed": None,
            "trainer_stats": {"roi": -2.00, "wins": 0, "runs": 2, "strike_rate": 0},
            "jockey_stats": {"roi": -5.50, "wins": 1, "runs": 14, "strike_rate": 7},
            "race_comments": []
        }
    ]
}

